sudo: false
rvm:
  - 2.5.0

env:
  - DOCKER_COMPOSE_VERSION=1.20.1

before_script:
  - docker-compose --version
  - docker-compose pull
  - docker-compose build
  - docker-compose up --no-start
  - docker-compose start
  - sleep 30 # Wait for databases to come online
  - docker ps

